import type { Metadata } from "next";
import Link from "next/link";
import BackToTop from "@/components/layout/BackToTop";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { getAbsoluteUrl } from "@/config/site";
import { getDistrictsBySide } from "@/content/districts/district-registry";
import { getDistrictPath, districtGuidePath } from "@/content/districts/district-routes";
import { homeContent } from "@/content/homeContent";

export const metadata: Metadata = { title: "İstanbul İlçe Rehberi | Şaban Durali", description: "İstanbul’un 39 ilçesi için kaynak temelli ilçe rehberleri.", alternates: { canonical: getAbsoluteUrl(districtGuidePath) } };

function DistrictGroup({ title, districts }: { title: string; districts: ReturnType<typeof getDistrictsBySide> }) { return <section><div className="flex flex-wrap items-baseline justify-between gap-3 border-b border-border pb-4"><h2 className="text-3xl leading-tight text-ivory">{title}</h2><p className="text-sm text-accent-strong">{districts.length} ilçe</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{districts.map((district) => <Link key={district.slug} href={getDistrictPath(district.slug)} className="group border border-border bg-[#17364D] p-4 transition-all hover:-translate-y-0.5 hover:border-[var(--accent-border-hover)] hover:bg-[#20445C] focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-4 focus-visible:outline-[var(--focus-ring)] sm:p-5"><p className="text-xs uppercase tracking-[0.16em] text-accent-strong">İlçe Rehberi</p><h3 className="mt-2 text-2xl leading-tight text-ivory">{district.name}</h3><span className="mt-4 inline-block text-sm text-muted underline decoration-border underline-offset-4 group-hover:text-accent-strong">Rehberi aç →</span></Link>)}</div></section>; }

export default function DistrictIndexPage() { const home = homeContent.tr; const european = getDistrictsBySide("avrupa"); const asian = getDistrictsBySide("anadolu"); return <div id="top" lang="tr"><Header locale="tr" anchors={home.anchors} content={home.header} homeHref="/" anchorPrefix="/" languageHrefs={{ tr: districtGuidePath, en: "/en" }} /><main className="bg-[#10263A] px-4 py-10 sm:px-6 sm:py-14 lg:py-18"><div className="mx-auto max-w-[1440px]"><header className="border-b border-border pb-8 sm:pb-10"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-accent-strong">İstanbul</p><h1 className="mt-3 text-4xl leading-[1.04] text-ivory sm:text-6xl">İstanbul İlçe Rehberi</h1><p className="mt-5 max-w-3xl text-base leading-7 text-muted sm:text-lg sm:leading-8">39 ilçeyi, doğrulanmış içerik ve kaynaklarla takip etmek için sade bir başlangıç noktası.</p><dl className="mt-7 grid gap-px overflow-hidden border border-border bg-border sm:grid-cols-3"><div className="bg-[#17364D] p-4 sm:p-5"><dt className="text-xs font-semibold uppercase tracking-[0.14em] text-accent-strong">Toplam</dt><dd className="mt-2 text-3xl text-ivory">39 ilçe</dd></div><div className="bg-[#17364D] p-4 sm:p-5"><dt className="text-xs font-semibold uppercase tracking-[0.14em] text-accent-strong">Avrupa Yakası</dt><dd className="mt-2 text-3xl text-ivory">{european.length} ilçe</dd></div><div className="bg-[#17364D] p-4 sm:p-5"><dt className="text-xs font-semibold uppercase tracking-[0.14em] text-accent-strong">Anadolu Yakası</dt><dd className="mt-2 text-3xl text-ivory">{asian.length} ilçe</dd></div></dl></header><div className="space-y-10 py-9 sm:space-y-12 sm:py-10"><DistrictGroup title="Avrupa Yakası — 25" districts={european} /><DistrictGroup title="Anadolu Yakası — 14" districts={asian} /></div></div></main><Footer id={home.anchors.contact} content={home.footer} /><BackToTop label={home.backToTopLabel} /></div>; }
