import Image from "next/image";
import Link from "next/link";
import BackToTop from "@/components/layout/BackToTop";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import DistrictMap from "@/components/districts/DistrictMap";
import DistrictNewsCard from "@/components/districts/DistrictNewsCard";
import { districtGuidePath, getDistrictNewsPath, getDistrictPath } from "@/content/districts/district-routes";
import type { District } from "@/content/districts/district-registry";
import type { DistrictGuide } from "@/content/districts/district-guide-data-source";
import type { PublicArticleSummary } from "@/content/articles/public-types";
import type { PublicPhoto } from "@/content/photos/types";
import { homeContent } from "@/content/homeContent";

const newsLimit = 3;
const photoLimit = 6;
const sectionClass = "border-t border-border bg-[#17334A] py-10 sm:py-14";
const investmentDisclaimer = "Önemli Bilgilendirme: Bu sayfada yer alan bilgi, veri, fiyat, kira, değerlendirme, yorum ve hesaplamalar yalnızca genel bilgilendirme ve araştırma amacıyla sunulmaktadır. Yatırım tavsiyesi değildir. Herhangi bir gayrimenkulün satın alınması, satılması veya kiralanmasına yönelik öneri ya da garanti niteliği taşımaz. Gayrimenkul kararlarında güncel resmî kayıtların, taşınmaza özgü hukuki ve teknik durumun ayrıca kontrol edilmesi gerekir.";
const planningDisclaimer = "Önemli Bilgilendirme: Bu içerik genel bilgilendirme ve araştırma amacıyla hazırlanmıştır. Yatırım tavsiyesi, hukuki danışmanlık veya taşınmaza özgü imar durumu belgesi değildir. Gayrimenkule ilişkin işlemlerde ilgili kurumların güncel resmî kayıtları esas alınmalıdır.";
const planningStatuses: Record<string, string> = { teklif: "Teklif", planlama: "Planlama", "belediye-meclisi-karari": "Belediye Meclisi Kararı", onay: "Onay", aski: "Askı", uygulama: "Uygulama", tamamlandi: "Tamamlandı" };

function EmptyState({ children }: { children: string }) { return <p className="mt-5 rounded-sm border border-border bg-surface p-5 text-sm leading-6 text-muted">{children}</p>; }
function hasText(...values: Array<string | null | undefined>) { return values.some((value) => value !== null && value !== undefined && value.trim() !== ""); }
function formatDate(value: string | null | undefined) { if (value === null || value === undefined) return null; const date = new Date(value); return Number.isFinite(date.getTime()) ? new Intl.DateTimeFormat("tr-TR", { dateStyle: "long" }).format(date) : null; }

export default function DistrictGuidePage({ district, guide, photos, research, news }: { district: District; guide: DistrictGuide | null; photos: PublicPhoto[]; research: PublicArticleSummary[]; news: PublicArticleSummary[] }) {
  const home = homeContent.tr;
  const facts = guide?.facts;
  const neighborhoods = guide?.neighborhoods ?? [];
  const highlightedNeighborhoods = neighborhoods.filter((item) => item.featured);
  const hasRealEstate = hasText(guide?.housingTexture, guide?.regionalAssessment, guide?.marketData?.source, guide?.marketData?.description) || guide?.marketData?.salePricePerM2 != null || guide?.marketData?.averageRent != null;
  const developments = guide?.planningDevelopments ?? [];
  const factItems = [["Yaka", district.side === "avrupa" ? "Avrupa Yakası" : "Anadolu Yakası"], ["Nüfus", facts?.population], ["Nüfus veri yılı", facts?.populationYear], ["Yüzölçümü", facts?.areaKm2 == null ? null : `${facts.areaKm2} km²`], ["Mahalle sayısı", facts?.neighborhoodCount], ["Komşu ilçeler", facts?.neighboringDistricts], ["Konum", facts?.locationSummary]].filter(([, value]) => value !== null && value !== undefined);

  return <div id="top" lang="tr"><Header locale="tr" anchors={home.anchors} content={home.header} homeHref="/" anchorPrefix="/" languageHrefs={{ tr: getDistrictPath(district.slug), en: "/en" }} /><main className="bg-[#11273A] px-4 py-10 [--surface:#1D3D55] [--surface-soft:#1D3D55] sm:px-6 sm:py-14 lg:py-18"><div className="mx-auto max-w-[1440px]">
    <nav aria-label="Breadcrumb" className="text-sm text-muted"><Link href={districtGuidePath} className="text-accent-soft hover:text-ivory">İstanbul İlçe Rehberi</Link><span aria-hidden="true"> / </span><span>{district.name}</span></nav>
    <header className="py-10 sm:py-14"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-accent-soft">İstanbul · {district.side === "avrupa" ? "Avrupa Yakası" : "Anadolu Yakası"}</p><h1 className="mt-4 text-5xl text-ivory sm:text-6xl">{district.name} İlçe Rehberi</h1><p className="mt-5 max-w-3xl text-lg text-muted">İlçeye ilişkin doğrulanmış içerikler, kaynaklar ve güncel gelişmeler burada derlenir.</p></header>
    <nav aria-label="Bölümler" className="mb-8 flex flex-wrap gap-x-5 gap-y-2 border-y border-border py-4 text-sm text-accent-soft"><a href="#tani">01 — İlçeyi Tanı</a><a href="#mahalleler">02 — Mahalleler</a><a href="#gayrimenkul">03 — Gayrimenkul</a><a href="#kareler">04 — İlçeden Kareler</a><a href="#imar">05 — Şehir & İmar Gelişmeleri</a><a href="#arastirmalar">06 — Araştırmalar</a><a href="#haberler">07 — İlçeden Haberler</a></nav>
    <section id="tani" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">01 — İLÇEYİ TANI</p><div className="mt-5 grid gap-5 lg:grid-cols-3">{[["Tarihçe", guide?.history], ["Yaşam", guide?.life], ["Ulaşım", guide?.transportation]].map(([heading, value]) => <section key={heading} className="border border-border bg-surface p-5"><h2 className="text-2xl text-ivory">{heading}</h2><p className="mt-3 whitespace-pre-line text-sm leading-6 text-muted">{value || "Bu başlık için henüz doğrulanmış içerik eklenmedi."}</p></section>)}</div><dl className="mt-5 grid gap-px overflow-hidden border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{factItems.map(([label, value]) => <div key={label} className="bg-surface p-4"><dt className="text-xs font-semibold uppercase tracking-[0.14em] text-accent-soft">{label}</dt><dd className="mt-2 text-sm text-ivory">{value}</dd></div>)}</dl></section>
    <section id="mahalleler" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">02 — MAHALLELER</p><h2 className="mt-3 text-3xl text-ivory">Mahalleler</h2><div className="mt-5"><DistrictMap district={district} /></div>{neighborhoods.length === 0 ? <EmptyState>Bu ilçe için güncel mahalle listesi henüz eklenmedi.</EmptyState> : <><ul className="mt-5 flex flex-wrap gap-2">{neighborhoods.map((item) => <li key={item.id ?? item.name} className="border border-border bg-surface px-3 py-2 text-sm text-muted">{item.name}</li>)}</ul>{highlightedNeighborhoods.length > 0 && <div className="mt-7"><h3 className="text-2xl text-ivory">Öne Çıkan Mahalleler</h3><div className="mt-5 grid gap-5 md:grid-cols-2">{highlightedNeighborhoods.map((item) => <article key={item.id ?? item.name} className="border border-border bg-surface p-5"><h4 className="text-2xl text-ivory">{item.name}</h4>{item.description && <p className="mt-3 text-sm text-muted">{item.description}</p>}</article>)}</div></div>}</>}</section>
    <section id="gayrimenkul" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">03 — GAYRİMENKUL</p><h2 className="mt-3 text-3xl text-ivory">Gayrimenkul</h2>{hasRealEstate ? <><div className="mt-5 grid gap-5 lg:grid-cols-2"><article className="border border-border bg-surface p-5"><h3 className="text-2xl text-ivory">Konut & yapı dokusu</h3><p className="mt-3 whitespace-pre-line text-sm text-muted">{guide?.housingTexture || "Bu başlık için henüz doğrulanmış içerik eklenmedi."}</p></article><article className="border border-border bg-surface p-5"><h3 className="text-2xl text-ivory">Bölgesel değerlendirme</h3><p className="mt-3 whitespace-pre-line text-sm text-muted">{guide?.regionalAssessment || "Bu başlık için henüz doğrulanmış içerik eklenmedi."}</p></article></div>{guide?.marketData && <dl className="mt-5 grid gap-4 border border-border bg-surface p-5 sm:grid-cols-2">{guide.marketData.salePricePerM2 != null && <div><dt className="text-xs text-accent-soft">Ortalama m² satış fiyatı</dt><dd className="text-lg text-ivory">{guide.marketData.salePricePerM2.toLocaleString("tr-TR")} TL</dd></div>}{guide.marketData.averageRent != null && <div><dt className="text-xs text-accent-soft">Ortalama kira</dt><dd className="text-lg text-ivory">{guide.marketData.averageRent.toLocaleString("tr-TR")} TL</dd></div>}{guide.marketData.dataDate && <div><dt className="text-xs text-accent-soft">Veri tarihi</dt><dd className="text-sm text-ivory">{formatDate(guide.marketData.dataDate)}</dd></div>}{guide.marketData.source && <div><dt className="text-xs text-accent-soft">Veri kaynağı</dt><dd className="text-sm text-ivory">{guide.marketData.source}</dd></div>}{guide.marketData.description && <div className="sm:col-span-2"><dt className="text-xs text-accent-soft">Not</dt><dd className="mt-1 text-sm text-muted">{guide.marketData.description}</dd></div>}</dl>}<p className="mt-5 border-l-4 border-accent-soft bg-surface-soft p-5 text-sm font-bold leading-6 text-ivory">{investmentDisclaimer}</p></> : <EmptyState>Bu ilçe için doğrulanmış gayrimenkul verisi henüz eklenmedi.</EmptyState>}</section>
    <section id="kareler" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">04 — İLÇEDEN KARELER</p><h2 className="mt-3 text-3xl text-ivory">{district.name}’den Kareler</h2>{photos.length === 0 ? <EmptyState>Bu ilçeden seçilmiş fotoğraflar henüz eklenmedi.</EmptyState> : <div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{photos.slice(0, photoLimit).map((photo) => <article key={photo.id} className="overflow-hidden border border-border bg-surface"><Image src={photo.image.src} alt={photo.image.alt} width={photo.image.width ?? 800} height={photo.image.height ?? 600} className="aspect-[4/3] w-full object-cover" /><div className="p-4"><h3 className="text-xl text-ivory">{photo.title}</h3>{photo.description && <p className="mt-2 text-sm leading-6 text-muted">{photo.description}</p>}<p className="mt-3 text-xs text-muted">{[photo.neighborhood ?? photo.locationName, formatDate(photo.takenAt), photo.dayPeriod === null ? null : photo.dayPeriod === "gece" ? "Gece" : "Gündüz", photo.districtPhotoCategory].filter(Boolean).join(" · ")}</p></div></article>)}</div>}</section>
    <section id="imar" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">05 — ŞEHİR & İMAR GELİŞMELERİ</p><h2 className="mt-3 text-3xl text-ivory">Şehir & İmar Gelişmeleri</h2>{developments.length === 0 ? <EmptyState>Bu ilçe için doğrulanmış şehircilik ve imar gelişmeleri henüz eklenmedi.</EmptyState> : <><div className="mt-5 space-y-4">{developments.map((item) => <article key={item.id ?? item.title} className="border border-border bg-surface p-5"><h3 className="text-2xl text-ivory">{item.title}</h3>{item.summary && <p className="mt-3 text-sm leading-6 text-muted">{item.summary}</p>}<dl className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm">{item.neighborhood && <div><dt className="inline text-accent-soft">Mahalle: </dt><dd className="inline text-muted">{item.neighborhood}</dd></div>}{formatDate(item.date) && <div><dt className="inline text-accent-soft">Tarih: </dt><dd className="inline text-muted">{formatDate(item.date)}</dd></div>}{item.status && <div><dt className="inline text-accent-soft">Durum: </dt><dd className="inline text-muted">{planningStatuses[item.status] ?? item.status}</dd></div>}{formatDate(item.checkedAt) && <div><dt className="inline text-accent-soft">Son kontrol: </dt><dd className="inline text-muted">{formatDate(item.checkedAt)}</dd></div>}</dl>{item.officialSource && <a href={item.officialSource} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-11 items-center text-sm text-accent-soft underline">Resmî kaynak ↗</a>}</article>)}</div><p className="mt-5 border-l-4 border-accent-soft bg-surface-soft p-5 text-sm font-bold leading-6 text-ivory">{planningDisclaimer}</p></>}</section>
    <section id="arastirmalar" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">06 — ARAŞTIRMALAR</p><h2 className="mt-3 text-3xl text-ivory">Araştırmalar</h2>{research.length === 0 ? <EmptyState>Bu ilçeye ilişkin araştırma ve analizler henüz eklenmedi.</EmptyState> : <div className="mt-5 grid gap-5 lg:grid-cols-2">{research.map((item) => <article key={item.id} className="overflow-hidden border border-border bg-surface">{item.featuredImage && <Image src={item.featuredImage.src} alt={item.featuredImage.alt} width={item.featuredImage.width ?? 960} height={item.featuredImage.height ?? 540} className="aspect-video w-full object-cover" />}<div className="p-5"><h3 className="text-2xl text-ivory">{item.title}</h3><p className="mt-3 text-sm text-muted">{item.summary}</p><Link href={`/makaleler/${item.slug}`} className="mt-4 inline-flex min-h-11 items-center text-sm font-semibold text-accent-soft underline">Araştırmayı Oku →</Link></div></article>)}</div>}</section>
    <section id="haberler" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">07 — İLÇEDEN HABERLER</p><h2 className="mt-3 text-3xl text-ivory">İlçeden Haberler</h2>{news.length === 0 ? <EmptyState>Bu ilçeye ilişkin seçilmiş güncel haberler henüz eklenmedi.</EmptyState> : <><div className="mt-5 grid gap-5 lg:grid-cols-3">{news.slice(0, newsLimit).map((item) => <DistrictNewsCard key={item.id} news={item} />)}</div>{news.length > newsLimit && <Link href={getDistrictNewsPath(district.slug)} className="mt-6 inline-flex min-h-11 items-center border border-accent px-5 text-sm font-semibold text-accent-soft hover:text-ivory">Tüm İlçe Haberleri →</Link>}</>}</section>
  </div></main><Footer id={home.anchors.contact} content={home.footer} /><BackToTop label={home.backToTopLabel} /></div>;
}
