import Image from "next/image";
import Link from "next/link";
import BackToTop from "@/components/layout/BackToTop";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import DistrictMap from "@/components/districts/DistrictMap";
import DistrictNewsCard from "@/components/districts/DistrictNewsCard";
import { districtGuidePath, getDistrictNewsPath, getDistrictPath } from "@/content/districts/district-routes";
import type { District } from "@/content/districts/district-registry";
import type { DistrictGuide } from "@/content/districts/district-guide-data-source";
import type { PublicArticleSummary } from "@/content/articles/public-types";
import type { PublicPhoto } from "@/content/photos/types";
import { homeContent } from "@/content/homeContent";

const newsLimit = 3;
const photoLimit = 6;
const sectionClass = "border-t border-border py-10 sm:py-14";
const investmentDisclaimer = "Önemli Bilgilendirme: Bu sayfada yer alan bilgi, veri, fiyat, kira, değerlendirme, yorum ve hesaplamalar yalnızca genel bilgilendirme ve araştırma amacıyla sunulmaktadır. Yatırım tavsiyesi değildir. Herhangi bir gayrimenkulün satın alınması, satılması veya kiralanmasına yönelik öneri ya da garanti niteliği taşımaz. Gayrimenkul kararlarında güncel resmî kayıtların, taşınmaza özgü hukuki ve teknik durumun ayrıca kontrol edilmesi gerekir.";
const planningDisclaimer = "Önemli Bilgilendirme: Bu içerik genel bilgilendirme ve araştırma amacıyla hazırlanmıştır. Yatırım tavsiyesi, hukuki danışmanlık veya taşınmaza özgü imar durumu belgesi değildir. Gayrimenkule ilişkin işlemlerde ilgili kurumların güncel resmî kayıtları esas alınmalıdır.";

function EmptyState() { return <p className="mt-5 rounded-sm border border-border bg-surface p-5 text-sm text-muted">Bu bölüm hazırlanıyor.</p>; }
function hasText(...values: Array<string | null | undefined>) { return values.some((value) => value !== null && value !== undefined && value.trim() !== ""); }

export default function DistrictGuidePage({ district, guide, photos, research, news }: { district: District; guide: DistrictGuide | null; photos: PublicPhoto[]; research: PublicArticleSummary[]; news: PublicArticleSummary[] }) {
  const home = homeContent.tr;
  const facts = guide?.facts;
  const neighborhoods = guide?.neighborhoods ?? [];
  const highlightedNeighborhoods = neighborhoods.filter((item) => item.featured);
  const hasRealEstate = hasText(guide?.housingTexture, guide?.regionalAssessment, guide?.marketData?.source, guide?.marketData?.description) || guide?.marketData?.salePricePerM2 != null || guide?.marketData?.averageRent != null;
  const developments = guide?.planningDevelopments ?? [];

  return <div id="top" lang="tr">
    <Header locale="tr" anchors={home.anchors} content={home.header} homeHref="/" anchorPrefix="/" languageHrefs={{ tr: getDistrictPath(district.slug), en: "/en" }} />
    <main className="px-4 py-10 sm:px-6 sm:py-14 lg:py-18"><div className="mx-auto max-w-6xl">
      <nav aria-label="Breadcrumb" className="text-sm text-muted"><Link href={districtGuidePath} className="text-accent-soft hover:text-ivory">İstanbul İlçe Rehberi</Link><span aria-hidden="true"> / </span><span>{district.name}</span></nav>
      <header className="py-10 sm:py-14"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-accent-soft">İstanbul · {district.side === "avrupa" ? "Avrupa Yakası" : "Anadolu Yakası"}</p><h1 className="mt-4 text-5xl text-ivory sm:text-6xl">{district.name} İlçe Rehberi</h1><p className="mt-5 max-w-3xl text-lg text-muted">İlçeye ilişkin doğrulanmış içerikler, kaynaklar ve güncel gelişmeler burada derlenir.</p></header>
      <nav aria-label="Bölümler" className="mb-8 flex flex-wrap gap-x-5 gap-y-2 border-y border-border py-4 text-sm text-accent-soft"><a href="#tani">01 — İlçeyi Tanı</a><a href="#mahalleler">02 — Mahalleler</a><a href="#gayrimenkul">03 — Gayrimenkul</a><a href="#kareler">04 — İlçeden Kareler</a>{developments.length > 0 && <a href="#imar">05 — Şehir & İmar Gelişmeleri</a>}{research.length > 0 && <a href="#arastirmalar">06 — Araştırmalar</a>}{news.length > 0 && <a href="#haberler">07 — İlçeden Haberler</a>}</nav>
      <section id="tani" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">01 — İLÇEYİ TANI</p><div className="mt-5 grid gap-5 lg:grid-cols-3">{[["Tarihçe", guide?.history], ["Yaşam", guide?.life], ["Ulaşım", guide?.transportation]].map(([heading, value]) => <section key={heading} className="border border-border bg-surface p-5"><h2 className="text-2xl text-ivory">{heading}</h2><p className="mt-3 whitespace-pre-line text-sm leading-6 text-muted">{value || "Bu bölüm hazırlanıyor."}</p></section>)}</div>{facts !== null && facts !== undefined && <dl className="mt-5 grid gap-px overflow-hidden border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{[["Yaka", district.side === "avrupa" ? "Avrupa Yakası" : "Anadolu Yakası"], ["Nüfus", facts.population], ["Nüfus veri yılı", facts.populationYear], ["Yüzölçümü", facts.areaKm2 == null ? null : `${facts.areaKm2} km²`], ["Mahalle sayısı", facts.neighborhoodCount], ["Komşu ilçeler", facts.neighboringDistricts], ["Konum", facts.locationSummary]].filter(([, value]) => value !== null && value !== undefined).map(([label, value]) => <div key={label} className="bg-surface p-4"><dt className="text-xs font-semibold uppercase tracking-[0.14em] text-accent-soft">{label}</dt><dd className="mt-2 text-sm text-ivory">{value}</dd></div>)}</dl>}<div className="mt-5"><DistrictMap district={district} /></div></section>
      <section id="mahalleler" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">02 — MAHALLELER</p><h2 className="mt-3 text-3xl text-ivory">Mahalleler</h2>{neighborhoods.length === 0 ? <EmptyState /> : <><ul className="mt-5 flex flex-wrap gap-2">{neighborhoods.map((item) => <li key={item.id ?? item.name} className="border border-border bg-surface px-3 py-2 text-sm text-muted">{item.name}</li>)}</ul>{highlightedNeighborhoods.length > 0 && <div className="mt-7 grid gap-5 md:grid-cols-2">{highlightedNeighborhoods.map((item) => <article key={item.id ?? item.name} className="border border-border bg-surface p-5"><h3 className="text-2xl text-ivory">{item.name}</h3>{item.description && <p className="mt-3 text-sm text-muted">{item.description}</p>}</article>)}</div>}</>}</section>
      <section id="gayrimenkul" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">03 — GAYRİMENKUL</p><h2 className="mt-3 text-3xl text-ivory">Gayrimenkul</h2>{hasRealEstate ? <><div className="mt-5 grid gap-5 lg:grid-cols-2"><article className="border border-border bg-surface p-5"><h3 className="text-2xl text-ivory">Konut & yapı dokusu</h3><p className="mt-3 whitespace-pre-line text-sm text-muted">{guide?.housingTexture}</p></article><article className="border border-border bg-surface p-5"><h3 className="text-2xl text-ivory">Bölgesel değerlendirme</h3><p className="mt-3 whitespace-pre-line text-sm text-muted">{guide?.regionalAssessment}</p></article></div>{guide?.marketData && <dl className="mt-5 grid gap-4 border border-border bg-surface p-5 sm:grid-cols-2">{guide.marketData.salePricePerM2 != null && <div><dt className="text-xs text-accent-soft">Ortalama m² satış fiyatı</dt><dd className="text-lg text-ivory">{guide.marketData.salePricePerM2.toLocaleString("tr-TR")} TL</dd></div>}{guide.marketData.averageRent != null && <div><dt className="text-xs text-accent-soft">Ortalama kira</dt><dd className="text-lg text-ivory">{guide.marketData.averageRent.toLocaleString("tr-TR")} TL</dd></div>}{guide.marketData.source && <div><dt className="text-xs text-accent-soft">Veri kaynağı</dt><dd className="text-sm text-ivory">{guide.marketData.source}</dd></div>}</dl>}<p className="mt-5 border-l-4 border-accent-soft bg-surface-soft p-5 text-sm font-bold leading-6 text-ivory">{investmentDisclaimer}</p></> : <EmptyState />}</section>
      <section id="kareler" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">04 — İLÇEDEN KARELER</p><h2 className="mt-3 text-3xl text-ivory">{district.name}’den Kareler</h2>{photos.length === 0 ? <EmptyState /> : <div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{photos.slice(0, photoLimit).map((photo) => <article key={photo.id} className="overflow-hidden border border-border bg-surface"><Image src={photo.image.src} alt={photo.image.alt} width={photo.image.width ?? 800} height={photo.image.height ?? 600} className="aspect-[4/3] w-full object-cover" /><div className="p-4"><h3 className="text-xl text-ivory">{photo.title}</h3><p className="mt-1 text-xs text-muted">{photo.neighborhood ?? photo.locationName}</p></div></article>)}</div>}</section>
      {developments.length > 0 && <section id="imar" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">05 — ŞEHİR & İMAR GELİŞMELERİ</p><div className="mt-5 space-y-4">{developments.map((item) => <article key={item.id ?? item.title} className="border border-border bg-surface p-5"><h2 className="text-2xl text-ivory">{item.title}</h2>{item.summary && <p className="mt-2 text-sm text-muted">{item.summary}</p>}{item.officialSource && <a href={item.officialSource} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm text-accent-soft underline">Resmî kaynak ↗</a>}</article>)}</div><p className="mt-5 border-l-4 border-accent-soft bg-surface-soft p-5 text-sm font-bold leading-6 text-ivory">{planningDisclaimer}</p></section>}
      {research.length > 0 && <section id="arastirmalar" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">06 — ARAŞTIRMALAR</p><div className="mt-5 grid gap-5 lg:grid-cols-2">{research.map((item) => <article key={item.id} className="border border-border bg-surface p-5"><h2 className="text-2xl text-ivory">{item.title}</h2><p className="mt-3 text-sm text-muted">{item.summary}</p><Link href={`/makaleler/${item.slug}`} className="mt-4 inline-flex min-h-11 items-center text-sm font-semibold text-accent-soft underline">Araştırmayı Oku →</Link></article>)}</div></section>}
      {news.length > 0 && <section id="haberler" className={sectionClass}><p className="text-xs font-semibold tracking-[0.18em] text-accent-soft">07 — İLÇEDEN HABERLER</p><h2 className="mt-3 text-3xl text-ivory">İlçeden Haberler</h2><div className="mt-5 grid gap-5 lg:grid-cols-3">{news.slice(0, newsLimit).map((item) => <DistrictNewsCard key={item.id} news={item} />)}</div>{news.length > newsLimit && <Link href={getDistrictNewsPath(district.slug)} className="mt-6 inline-flex min-h-11 items-center border border-accent px-5 text-sm font-semibold text-accent-soft hover:text-ivory">Tüm İlçe Haberleri →</Link>}</section>}
    </div></main><Footer id={home.anchors.contact} content={home.footer} /><BackToTop label={home.backToTopLabel} />
  </div>;
}
