/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    articles: Article;
    books: Book;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('tr' | 'en') | ('tr' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'tr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Görseli, içeriği görmeyen bir kullanıcı için kısa ve anlamlı biçimde açıklayın.
   */
  alt: string;
  description?: string | null;
  sourceCopyright?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  /**
   * Başlıktan otomatik oluşur; gerekirse elle düzenlenebilir ve başlık değiştiğinde korunur.
   */
  slug: string;
  description?: string | null;
  /**
   * Kategorilerin yönetim panelindeki sıralamasını belirlemek için kullanılır.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  title: string;
  /**
   * Başlıktan otomatik oluşur; gerekirse elle düzenlenebilir ve başlık değiştiğinde korunur.
   */
  slug: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categories: (string | Category)[];
  featuredImage?: (string | null) | Media;
  /**
   * Görseli, bu makaledeki bağlamına göre açıklayan alternatif metin.
   */
  featuredImageAlt?: string | null;
  featured?: boolean | null;
  /**
   * İlk yayında otomatik atanır; gerekirse elle düzenlenebilir.
   */
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: string;
  title: string;
  /**
   * Başlıktan otomatik oluşur; gerekirse elle düzenlenebilir.
   */
  slug: string;
  language: 'tr' | 'en';
  originalTitle?: string | null;
  authors?:
    | {
        name: string;
        slug: string;
        id?: string | null;
      }[]
    | null;
  translator?: string | null;
  publisher?: string | null;
  originalPublisher?: string | null;
  publicationYear?: number | null;
  originalPublicationYear?: number | null;
  edition?: string | null;
  pageCount?: number | null;
  isbn10?: string | null;
  isbn13?: string | null;
  coverImage?: (string | null) | Media;
  /**
   * Boş bırakılırsa medya kaydındaki alternatif metin kullanılır.
   */
  coverImageAlt?: string | null;
  category?:
    | (
        | 'business_and_management'
        | 'psychology_and_behavior'
        | 'sales_and_negotiation'
        | 'learning_and_education'
        | 'artificial_intelligence_and_technology'
        | 'real_estate_and_investment'
        | 'personal_development'
        | 'biography_and_history'
        | 'economics_and_finance'
        | 'other'
      )
    | null;
  tags?:
    | {
        slug: string;
        labelTr: string;
        labelEn: string;
        aliases?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  readingStatus: 'planned' | 'reading' | 'completed' | 'paused' | 'abandoned';
  /**
   * Public erişim için published seçilmeli; yayın tarihi gelmiş ve SEO index açık olmalıdır.
   */
  reviewStatus: 'draft' | 'in_review' | 'scheduled' | 'published' | 'archived';
  startedAt?: string | null;
  completedAt?: string | null;
  /**
   * Gelecekteki bir tarih planlı yayını; boş değer public erişimin kapalı kalmasını sağlar.
   */
  publishedAt?: string | null;
  summary: string;
  keyIdeas?:
    | {
        title: string;
        description: string;
        order: number;
        id?: string | null;
      }[]
    | null;
  strengths?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  weaknesses?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  whoShouldRead?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  whoShouldNotRead?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  applicationNotes?:
    | {
        title: string;
        description: string;
        action: string;
        order: number;
        id?: string | null;
      }[]
    | null;
  personalEvaluation: string;
  rating?: number | null;
  quotes?:
    | {
        text: string;
        page?: number | null;
        note?: string | null;
        order: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Bu incelemenin Türkçe veya İngilizce karşılığını seçin.
   */
  translation?: (string | null) | Book;
  translationStatus: 'none' | 'pending' | 'in_progress' | 'completed' | 'outdated';
  relatedBooks?: (string | Book)[] | null;
  authorId?: (string | null) | User;
  editorId?: (string | null) | User;
  featured?: boolean | null;
  showOnHomepage?: boolean | null;
  seo: {
    title: string;
    description: string;
    canonical?: string | null;
    index: boolean;
    follow: boolean;
    openGraphTitle?: string | null;
    openGraphDescription?: string | null;
    openGraphImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  description?: T;
  sourceCopyright?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  categories?: T;
  featuredImage?: T;
  featuredImageAlt?: T;
  featured?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  language?: T;
  originalTitle?: T;
  authors?:
    | T
    | {
        name?: T;
        slug?: T;
        id?: T;
      };
  translator?: T;
  publisher?: T;
  originalPublisher?: T;
  publicationYear?: T;
  originalPublicationYear?: T;
  edition?: T;
  pageCount?: T;
  isbn10?: T;
  isbn13?: T;
  coverImage?: T;
  coverImageAlt?: T;
  category?: T;
  tags?:
    | T
    | {
        slug?: T;
        labelTr?: T;
        labelEn?: T;
        aliases?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  readingStatus?: T;
  reviewStatus?: T;
  startedAt?: T;
  completedAt?: T;
  publishedAt?: T;
  summary?: T;
  keyIdeas?:
    | T
    | {
        title?: T;
        description?: T;
        order?: T;
        id?: T;
      };
  strengths?:
    | T
    | {
        value?: T;
        id?: T;
      };
  weaknesses?:
    | T
    | {
        value?: T;
        id?: T;
      };
  whoShouldRead?:
    | T
    | {
        value?: T;
        id?: T;
      };
  whoShouldNotRead?:
    | T
    | {
        value?: T;
        id?: T;
      };
  applicationNotes?:
    | T
    | {
        title?: T;
        description?: T;
        action?: T;
        order?: T;
        id?: T;
      };
  personalEvaluation?: T;
  rating?: T;
  quotes?:
    | T
    | {
        text?: T;
        page?: T;
        note?: T;
        order?: T;
        id?: T;
      };
  translation?: T;
  translationStatus?: T;
  relatedBooks?: T;
  authorId?: T;
  editorId?: T;
  featured?: T;
  showOnHomepage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        index?: T;
        follow?: T;
        openGraphTitle?: T;
        openGraphDescription?: T;
        openGraphImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}